networks:
  ai_network:
    driver: bridge

services:
  montreal-forced-aligner:
    image: montreal-forced-aligner:1.0
    container_name: montreal-forced-aligner
    restart: always
    runtime: nvidia
    privileged: true
    volumes:
      - d:/AI/Montreal-Forced-Aligner/results:/code/results
      - d:/AI/Montreal-Forced-Aligner/error:/code/error
      - d:/AI/Montreal-Forced-Aligner/logs:/code/logs
    environment:
      - TQDM_DISABLE=1 # 全局关闭进度条显示
      - PYTHONUNBUFFERED=1 # 取消标准输出缓冲
      - CUDA_VISIBLE_DEVICES=0
      - ASR_URL=http://host.docker.internal:7868/api/v1/asr
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:1024
    tty: true  # 分配伪终端
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    shm_size: '32g'
    ports:
      - '8119:8119'
    command: python /code/api.py
    networks:
      - ai_network
